package cn.polarismesh.agent.plugin.nacos.asm;

import cn.polarismesh.agent.plugin.nacos.exception.UnsupportedNacosClientException;
import org.objectweb.asm.*;


public class NamingClientProxyGenerator implements AsmDynamicClassGenerator {

    public byte[] generate() {

        try {
            return generate21();
        } catch (Exception e) {
            throw new UnsupportedNacosClientException(e);
        }
    }

    private byte[] generate21() {

        ClassWriter classWriter = new ClassWriter(0);
        FieldVisitor fieldVisitor;
        RecordComponentVisitor recordComponentVisitor;
        MethodVisitor methodVisitor;
        AnnotationVisitor annotationVisitor0;

        classWriter.visit(V1_8, ACC_PUBLIC | ACC_SUPER, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", null, "java/lang/Object", new String[]{"com/alibaba/nacos/client/naming/remote/NamingClientProxy"});

        classWriter.visitSource("DynamicNamingClientProxy.java", null);

        {
            fieldVisitor = classWriter.visitField(ACC_PRIVATE, "clientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;", null, null);
            fieldVisitor.visitEnd();
        }
        {
            fieldVisitor = classWriter.visitField(ACC_PRIVATE, "otherClientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;", null, null);
            fieldVisitor.visitEnd();
        }
        {
            fieldVisitor = classWriter.visitField(ACC_PRIVATE, "assist", "Lcn/polarismesh/agent/plugin/nacos/delegate/NamingClientProxyAssist;", null, null);
            fieldVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "<init>", "(Ljava/lang/String;Lcom/alibaba/nacos/client/naming/cache/ServiceInfoHolder;Ljava/util/Properties;Lcom/alibaba/nacos/client/naming/event/InstancesChangeNotifier;)V", null, new String[]{"com/alibaba/nacos/api/exception/NacosException"});
            methodVisitor.visitCode();
            Label label0 = new Label();
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(31, label0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
            Label label1 = new Label();
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLineNumber(32, label1);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitTypeInsn(NEW, "com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate");
            methodVisitor.visitInsn(DUP);
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitVarInsn(ALOAD, 3);
            methodVisitor.visitVarInsn(ALOAD, 4);
            methodVisitor.visitMethodInsn(INVOKESPECIAL, "com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate", "<init>", "(Ljava/lang/String;Lcom/alibaba/nacos/client/naming/cache/ServiceInfoHolder;Ljava/util/Properties;Lcom/alibaba/nacos/client/naming/event/InstancesChangeNotifier;)V", false);
            methodVisitor.visitFieldInsn(PUTFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "clientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            Label label2 = new Label();
            methodVisitor.visitLabel(label2);
            methodVisitor.visitLineNumber(33, label2);
            methodVisitor.visitLdcInsn("other.nacos.server.addr");
            methodVisitor.visitMethodInsn(INVOKESTATIC, "java/lang/System", "getProperty", "(Ljava/lang/String;)Ljava/lang/String;", false);
            methodVisitor.visitVarInsn(ASTORE, 5);
            Label label3 = new Label();
            methodVisitor.visitLabel(label3);
            methodVisitor.visitLineNumber(36, label3);
            methodVisitor.visitTypeInsn(NEW, "java/util/Properties");
            methodVisitor.visitInsn(DUP);
            methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/util/Properties", "<init>", "()V", false);
            methodVisitor.visitVarInsn(ASTORE, 6);
            Label label4 = new Label();
            methodVisitor.visitLabel(label4);
            methodVisitor.visitLineNumber(37, label4);
            methodVisitor.visitVarInsn(ALOAD, 6);
            methodVisitor.visitVarInsn(ALOAD, 3);
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/util/Properties", "putAll", "(Ljava/util/Map;)V", false);
            Label label5 = new Label();
            methodVisitor.visitLabel(label5);
            methodVisitor.visitLineNumber(38, label5);
            methodVisitor.visitVarInsn(ALOAD, 6);
            methodVisitor.visitLdcInsn("serverAddr");
            methodVisitor.visitVarInsn(ALOAD, 5);
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/util/Properties", "setProperty", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Object;", false);
            methodVisitor.visitInsn(POP);
            Label label6 = new Label();
            methodVisitor.visitLabel(label6);
            methodVisitor.visitLineNumber(39, label6);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitTypeInsn(NEW, "com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate");
            methodVisitor.visitInsn(DUP);
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitVarInsn(ALOAD, 6);
            methodVisitor.visitVarInsn(ALOAD, 4);
            methodVisitor.visitMethodInsn(INVOKESPECIAL, "com/alibaba/nacos/client/naming/remote/NamingClientProxyDelegate", "<init>", "(Ljava/lang/String;Lcom/alibaba/nacos/client/naming/cache/ServiceInfoHolder;Ljava/util/Properties;Lcom/alibaba/nacos/client/naming/event/InstancesChangeNotifier;)V", false);
            methodVisitor.visitFieldInsn(PUTFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "otherClientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            Label label7 = new Label();
            methodVisitor.visitLabel(label7);
            methodVisitor.visitLineNumber(41, label7);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitTypeInsn(NEW, "cn/polarismesh/agent/plugin/nacos/delegate/NamingClientProxyAssist");
            methodVisitor.visitInsn(DUP);
            methodVisitor.visitMethodInsn(INVOKESPECIAL, "cn/polarismesh/agent/plugin/nacos/delegate/NamingClientProxyAssist", "<init>", "()V", false);
            methodVisitor.visitFieldInsn(PUTFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "assist", "Lcn/polarismesh/agent/plugin/nacos/delegate/NamingClientProxyAssist;");
            Label label8 = new Label();
            methodVisitor.visitLabel(label8);
            methodVisitor.visitLineNumber(42, label8);
            methodVisitor.visitInsn(RETURN);
            Label label9 = new Label();
            methodVisitor.visitLabel(label9);
            methodVisitor.visitLocalVariable("this", "Lcn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy;", null, label0, label9, 0);
            methodVisitor.visitLocalVariable("namespace", "Ljava/lang/String;", null, label0, label9, 1);
            methodVisitor.visitLocalVariable("serviceInfoHolder", "Lcom/alibaba/nacos/client/naming/cache/ServiceInfoHolder;", null, label0, label9, 2);
            methodVisitor.visitLocalVariable("properties", "Ljava/util/Properties;", null, label0, label9, 3);
            methodVisitor.visitLocalVariable("changeNotifier", "Lcom/alibaba/nacos/client/naming/event/InstancesChangeNotifier;", null, label0, label9, 4);
            methodVisitor.visitLocalVariable("otherNacosDomain", "Ljava/lang/String;", null, label3, label9, 5);
            methodVisitor.visitLocalVariable("otherProperties", "Ljava/util/Properties;", null, label4, label9, 6);
            methodVisitor.visitMaxs(7, 7);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "registerService", "(Ljava/lang/String;Ljava/lang/String;Lcom/alibaba/nacos/api/naming/pojo/Instance;)V", null, new String[]{"com/alibaba/nacos/api/exception/NacosException"});
            methodVisitor.visitCode();
            Label label0 = new Label();
            Label label1 = new Label();
            Label label2 = new Label();
            methodVisitor.visitTryCatchBlock(label0, label1, label2, "java/lang/Exception");
            Label label3 = new Label();
            Label label4 = new Label();
            Label label5 = new Label();
            methodVisitor.visitTryCatchBlock(label3, label4, label5, "java/lang/Exception");
            Label label6 = new Label();
            Label label7 = new Label();
            Label label8 = new Label();
            methodVisitor.visitTryCatchBlock(label6, label7, label8, "java/lang/Exception");
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(47, label0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "assist", "Lcn/polarismesh/agent/plugin/nacos/delegate/NamingClientProxyAssist;");
            methodVisitor.visitVarInsn(ALOAD, 3);
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "cn/polarismesh/agent/plugin/nacos/delegate/NamingClientProxyAssist", "fillMetadata", "(Ljava/lang/Object;)V", false);
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLineNumber(50, label1);
            methodVisitor.visitJumpInsn(GOTO, label3);
            methodVisitor.visitLabel(label2);
            methodVisitor.visitLineNumber(48, label2);
            methodVisitor.visitFrame(Opcodes.F_SAME1, 0, null, 1, new Object[]{"java/lang/Exception"});
            methodVisitor.visitVarInsn(ASTORE, 4);
            Label label9 = new Label();
            methodVisitor.visitLabel(label9);
            methodVisitor.visitLineNumber(49, label9);
            methodVisitor.visitFieldInsn(GETSTATIC, "com/alibaba/nacos/client/utils/LogUtils", "NAMING_LOGGER", "Lorg/slf4j/Logger;");
            methodVisitor.visitLdcInsn("fillMetadata failed ");
            methodVisitor.visitVarInsn(ALOAD, 4);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "org/slf4j/Logger", "error", "(Ljava/lang/String;Ljava/lang/Throwable;)V", true);
            methodVisitor.visitLabel(label3);
            methodVisitor.visitLineNumber(52, label3);
            methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "clientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitVarInsn(ALOAD, 3);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/alibaba/nacos/client/naming/remote/NamingClientProxy", "registerService", "(Ljava/lang/String;Ljava/lang/String;Lcom/alibaba/nacos/api/naming/pojo/Instance;)V", true);
            methodVisitor.visitLabel(label4);
            methodVisitor.visitLineNumber(55, label4);
            methodVisitor.visitJumpInsn(GOTO, label6);
            methodVisitor.visitLabel(label5);
            methodVisitor.visitLineNumber(53, label5);
            methodVisitor.visitFrame(Opcodes.F_SAME1, 0, null, 1, new Object[]{"java/lang/Exception"});
            methodVisitor.visitVarInsn(ASTORE, 4);
            Label label10 = new Label();
            methodVisitor.visitLabel(label10);
            methodVisitor.visitLineNumber(54, label10);
            methodVisitor.visitFieldInsn(GETSTATIC, "com/alibaba/nacos/client/utils/LogUtils", "NAMING_LOGGER", "Lorg/slf4j/Logger;");
            methodVisitor.visitLdcInsn("DynamicNamingClientProxy clientProxy registerService err.");
            methodVisitor.visitVarInsn(ALOAD, 4);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "org/slf4j/Logger", "error", "(Ljava/lang/String;Ljava/lang/Throwable;)V", true);
            methodVisitor.visitLabel(label6);
            methodVisitor.visitLineNumber(57, label6);
            methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "otherClientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitVarInsn(ALOAD, 3);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/alibaba/nacos/client/naming/remote/NamingClientProxy", "registerService", "(Ljava/lang/String;Ljava/lang/String;Lcom/alibaba/nacos/api/naming/pojo/Instance;)V", true);
            methodVisitor.visitLabel(label7);
            methodVisitor.visitLineNumber(60, label7);
            Label label11 = new Label();
            methodVisitor.visitJumpInsn(GOTO, label11);
            methodVisitor.visitLabel(label8);
            methodVisitor.visitLineNumber(58, label8);
            methodVisitor.visitFrame(Opcodes.F_SAME1, 0, null, 1, new Object[]{"java/lang/Exception"});
            methodVisitor.visitVarInsn(ASTORE, 4);
            Label label12 = new Label();
            methodVisitor.visitLabel(label12);
            methodVisitor.visitLineNumber(59, label12);
            methodVisitor.visitFieldInsn(GETSTATIC, "com/alibaba/nacos/client/utils/LogUtils", "NAMING_LOGGER", "Lorg/slf4j/Logger;");
            methodVisitor.visitLdcInsn("DynamicNamingClientProxy otherClientProxy registerService err.");
            methodVisitor.visitVarInsn(ALOAD, 4);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "org/slf4j/Logger", "error", "(Ljava/lang/String;Ljava/lang/Throwable;)V", true);
            methodVisitor.visitLabel(label11);
            methodVisitor.visitLineNumber(61, label11);
            methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
            methodVisitor.visitInsn(RETURN);
            Label label13 = new Label();
            methodVisitor.visitLabel(label13);
            methodVisitor.visitLocalVariable("e", "Ljava/lang/Exception;", null, label9, label3, 4);
            methodVisitor.visitLocalVariable("exp", "Ljava/lang/Exception;", null, label10, label6, 4);
            methodVisitor.visitLocalVariable("exp", "Ljava/lang/Exception;", null, label12, label11, 4);
            methodVisitor.visitLocalVariable("this", "Lcn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy;", null, label0, label13, 0);
            methodVisitor.visitLocalVariable("serviceName", "Ljava/lang/String;", null, label0, label13, 1);
            methodVisitor.visitLocalVariable("groupName", "Ljava/lang/String;", null, label0, label13, 2);
            methodVisitor.visitLocalVariable("instance", "Lcom/alibaba/nacos/api/naming/pojo/Instance;", null, label0, label13, 3);
            methodVisitor.visitMaxs(4, 5);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "deregisterService", "(Ljava/lang/String;Ljava/lang/String;Lcom/alibaba/nacos/api/naming/pojo/Instance;)V", null, new String[]{"com/alibaba/nacos/api/exception/NacosException"});
            methodVisitor.visitCode();
            Label label0 = new Label();
            Label label1 = new Label();
            Label label2 = new Label();
            methodVisitor.visitTryCatchBlock(label0, label1, label2, "java/lang/Exception");
            Label label3 = new Label();
            Label label4 = new Label();
            Label label5 = new Label();
            methodVisitor.visitTryCatchBlock(label3, label4, label5, "java/lang/Exception");
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(67, label0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "clientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitVarInsn(ALOAD, 3);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/alibaba/nacos/client/naming/remote/NamingClientProxy", "deregisterService", "(Ljava/lang/String;Ljava/lang/String;Lcom/alibaba/nacos/api/naming/pojo/Instance;)V", true);
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLineNumber(70, label1);
            methodVisitor.visitJumpInsn(GOTO, label3);
            methodVisitor.visitLabel(label2);
            methodVisitor.visitLineNumber(68, label2);
            methodVisitor.visitFrame(Opcodes.F_SAME1, 0, null, 1, new Object[]{"java/lang/Exception"});
            methodVisitor.visitVarInsn(ASTORE, 4);
            Label label6 = new Label();
            methodVisitor.visitLabel(label6);
            methodVisitor.visitLineNumber(69, label6);
            methodVisitor.visitFieldInsn(GETSTATIC, "com/alibaba/nacos/client/utils/LogUtils", "NAMING_LOGGER", "Lorg/slf4j/Logger;");
            methodVisitor.visitLdcInsn("DynamicNamingClientProxy clientProxy deregisterService err.");
            methodVisitor.visitVarInsn(ALOAD, 4);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "org/slf4j/Logger", "error", "(Ljava/lang/String;Ljava/lang/Throwable;)V", true);
            methodVisitor.visitLabel(label3);
            methodVisitor.visitLineNumber(72, label3);
            methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "otherClientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitVarInsn(ALOAD, 3);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/alibaba/nacos/client/naming/remote/NamingClientProxy", "deregisterService", "(Ljava/lang/String;Ljava/lang/String;Lcom/alibaba/nacos/api/naming/pojo/Instance;)V", true);
            methodVisitor.visitLabel(label4);
            methodVisitor.visitLineNumber(75, label4);
            Label label7 = new Label();
            methodVisitor.visitJumpInsn(GOTO, label7);
            methodVisitor.visitLabel(label5);
            methodVisitor.visitLineNumber(73, label5);
            methodVisitor.visitFrame(Opcodes.F_SAME1, 0, null, 1, new Object[]{"java/lang/Exception"});
            methodVisitor.visitVarInsn(ASTORE, 4);
            Label label8 = new Label();
            methodVisitor.visitLabel(label8);
            methodVisitor.visitLineNumber(74, label8);
            methodVisitor.visitFieldInsn(GETSTATIC, "com/alibaba/nacos/client/utils/LogUtils", "NAMING_LOGGER", "Lorg/slf4j/Logger;");
            methodVisitor.visitLdcInsn("DynamicNamingClientProxy otherClientProxy deregisterService err.");
            methodVisitor.visitVarInsn(ALOAD, 4);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "org/slf4j/Logger", "error", "(Ljava/lang/String;Ljava/lang/Throwable;)V", true);
            methodVisitor.visitLabel(label7);
            methodVisitor.visitLineNumber(76, label7);
            methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
            methodVisitor.visitInsn(RETURN);
            Label label9 = new Label();
            methodVisitor.visitLabel(label9);
            methodVisitor.visitLocalVariable("exp", "Ljava/lang/Exception;", null, label6, label3, 4);
            methodVisitor.visitLocalVariable("exp", "Ljava/lang/Exception;", null, label8, label7, 4);
            methodVisitor.visitLocalVariable("this", "Lcn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy;", null, label0, label9, 0);
            methodVisitor.visitLocalVariable("serviceName", "Ljava/lang/String;", null, label0, label9, 1);
            methodVisitor.visitLocalVariable("groupName", "Ljava/lang/String;", null, label0, label9, 2);
            methodVisitor.visitLocalVariable("instance", "Lcom/alibaba/nacos/api/naming/pojo/Instance;", null, label0, label9, 3);
            methodVisitor.visitMaxs(4, 5);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "updateInstance", "(Ljava/lang/String;Ljava/lang/String;Lcom/alibaba/nacos/api/naming/pojo/Instance;)V", null, new String[]{"com/alibaba/nacos/api/exception/NacosException"});
            methodVisitor.visitCode();
            Label label0 = new Label();
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(81, label0);
            methodVisitor.visitInsn(RETURN);
            Label label1 = new Label();
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLocalVariable("this", "Lcn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy;", null, label0, label1, 0);
            methodVisitor.visitLocalVariable("serviceName", "Ljava/lang/String;", null, label0, label1, 1);
            methodVisitor.visitLocalVariable("groupName", "Ljava/lang/String;", null, label0, label1, 2);
            methodVisitor.visitLocalVariable("instance", "Lcom/alibaba/nacos/api/naming/pojo/Instance;", null, label0, label1, 3);
            methodVisitor.visitMaxs(0, 4);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "queryInstancesOfService", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IZ)Lcom/alibaba/nacos/api/naming/pojo/ServiceInfo;", null, new String[]{"com/alibaba/nacos/api/exception/NacosException"});
            methodVisitor.visitCode();
            Label label0 = new Label();
            Label label1 = new Label();
            Label label2 = new Label();
            methodVisitor.visitTryCatchBlock(label0, label1, label2, "java/lang/Exception");
            Label label3 = new Label();
            Label label4 = new Label();
            Label label5 = new Label();
            methodVisitor.visitTryCatchBlock(label3, label4, label5, "java/lang/Exception");
            Label label6 = new Label();
            Label label7 = new Label();
            Label label8 = new Label();
            methodVisitor.visitTryCatchBlock(label6, label7, label8, "java/lang/Exception");
            Label label9 = new Label();
            methodVisitor.visitLabel(label9);
            methodVisitor.visitLineNumber(86, label9);
            methodVisitor.visitInsn(ACONST_NULL);
            methodVisitor.visitVarInsn(ASTORE, 6);
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(88, label0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "clientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitVarInsn(ALOAD, 3);
            methodVisitor.visitVarInsn(ILOAD, 4);
            methodVisitor.visitVarInsn(ILOAD, 5);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/alibaba/nacos/client/naming/remote/NamingClientProxy", "queryInstancesOfService", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IZ)Lcom/alibaba/nacos/api/naming/pojo/ServiceInfo;", true);
            methodVisitor.visitVarInsn(ASTORE, 6);
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLineNumber(91, label1);
            Label label10 = new Label();
            methodVisitor.visitJumpInsn(GOTO, label10);
            methodVisitor.visitLabel(label2);
            methodVisitor.visitLineNumber(89, label2);
            methodVisitor.visitFrame(Opcodes.F_FULL, 7, new Object[]{"cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "java/lang/String", "java/lang/String", "java/lang/String", Opcodes.INTEGER, Opcodes.INTEGER, "com/alibaba/nacos/api/naming/pojo/ServiceInfo"}, 1, new Object[]{"java/lang/Exception"});
            methodVisitor.visitVarInsn(ASTORE, 7);
            Label label11 = new Label();
            methodVisitor.visitLabel(label11);
            methodVisitor.visitLineNumber(90, label11);
            methodVisitor.visitFieldInsn(GETSTATIC, "com/alibaba/nacos/client/utils/LogUtils", "NAMING_LOGGER", "Lorg/slf4j/Logger;");
            methodVisitor.visitLdcInsn("DynamicNamingClientProxy queryInstancesOfService clientProxy queryInstancesOfService err.");
            methodVisitor.visitVarInsn(ALOAD, 7);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "org/slf4j/Logger", "error", "(Ljava/lang/String;Ljava/lang/Throwable;)V", true);
            methodVisitor.visitLabel(label10);
            methodVisitor.visitLineNumber(92, label10);
            methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
            methodVisitor.visitInsn(ACONST_NULL);
            methodVisitor.visitVarInsn(ASTORE, 7);
            methodVisitor.visitLabel(label3);
            methodVisitor.visitLineNumber(94, label3);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "otherClientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitVarInsn(ALOAD, 3);
            methodVisitor.visitVarInsn(ILOAD, 4);
            methodVisitor.visitVarInsn(ILOAD, 5);
            Label label12 = new Label();
            methodVisitor.visitLabel(label12);
            methodVisitor.visitLineNumber(95, label12);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/alibaba/nacos/client/naming/remote/NamingClientProxy", "queryInstancesOfService", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IZ)Lcom/alibaba/nacos/api/naming/pojo/ServiceInfo;", true);
            methodVisitor.visitVarInsn(ASTORE, 7);
            methodVisitor.visitLabel(label4);
            methodVisitor.visitLineNumber(98, label4);
            methodVisitor.visitJumpInsn(GOTO, label6);
            methodVisitor.visitLabel(label5);
            methodVisitor.visitLineNumber(96, label5);
            methodVisitor.visitFrame(Opcodes.F_FULL, 8, new Object[]{"cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "java/lang/String", "java/lang/String", "java/lang/String", Opcodes.INTEGER, Opcodes.INTEGER, "com/alibaba/nacos/api/naming/pojo/ServiceInfo", "com/alibaba/nacos/api/naming/pojo/ServiceInfo"}, 1, new Object[]{"java/lang/Exception"});
            methodVisitor.visitVarInsn(ASTORE, 8);
            Label label13 = new Label();
            methodVisitor.visitLabel(label13);
            methodVisitor.visitLineNumber(97, label13);
            methodVisitor.visitFieldInsn(GETSTATIC, "com/alibaba/nacos/client/utils/LogUtils", "NAMING_LOGGER", "Lorg/slf4j/Logger;");
            methodVisitor.visitLdcInsn("DynamicNamingClientProxy queryInstancesOfService otherClientProxy queryInstancesOfService err.");
            methodVisitor.visitVarInsn(ALOAD, 8);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "org/slf4j/Logger", "error", "(Ljava/lang/String;Ljava/lang/Throwable;)V", true);
            methodVisitor.visitLabel(label6);
            methodVisitor.visitLineNumber(101, label6);
            methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "assist", "Lcn/polarismesh/agent/plugin/nacos/delegate/NamingClientProxyAssist;");
            methodVisitor.visitVarInsn(ALOAD, 6);
            methodVisitor.visitVarInsn(ALOAD, 7);
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "cn/polarismesh/agent/plugin/nacos/delegate/NamingClientProxyAssist", "mergeInstances", "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;", false);
            methodVisitor.visitTypeInsn(CHECKCAST, "com/alibaba/nacos/api/naming/pojo/ServiceInfo");
            methodVisitor.visitLabel(label7);
            methodVisitor.visitInsn(ARETURN);
            methodVisitor.visitLabel(label8);
            methodVisitor.visitLineNumber(102, label8);
            methodVisitor.visitFrame(Opcodes.F_SAME1, 0, null, 1, new Object[]{"java/lang/Exception"});
            methodVisitor.visitVarInsn(ASTORE, 8);
            Label label14 = new Label();
            methodVisitor.visitLabel(label14);
            methodVisitor.visitLineNumber(103, label14);
            methodVisitor.visitFieldInsn(GETSTATIC, "com/alibaba/nacos/client/utils/LogUtils", "NAMING_LOGGER", "Lorg/slf4j/Logger;");
            methodVisitor.visitLdcInsn("DynamicNamingClientProxy queryInstancesOfService mergeInstances failed");
            methodVisitor.visitVarInsn(ALOAD, 8);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "org/slf4j/Logger", "error", "(Ljava/lang/String;Ljava/lang/Throwable;)V", true);
            Label label15 = new Label();
            methodVisitor.visitLabel(label15);
            methodVisitor.visitLineNumber(104, label15);
            methodVisitor.visitVarInsn(ALOAD, 6);
            methodVisitor.visitInsn(ARETURN);
            Label label16 = new Label();
            methodVisitor.visitLabel(label16);
            methodVisitor.visitLocalVariable("exp", "Ljava/lang/Exception;", null, label11, label10, 7);
            methodVisitor.visitLocalVariable("exp", "Ljava/lang/Exception;", null, label13, label6, 8);
            methodVisitor.visitLocalVariable("e", "Ljava/lang/Exception;", null, label14, label16, 8);
            methodVisitor.visitLocalVariable("this", "Lcn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy;", null, label9, label16, 0);
            methodVisitor.visitLocalVariable("serviceName", "Ljava/lang/String;", null, label9, label16, 1);
            methodVisitor.visitLocalVariable("groupName", "Ljava/lang/String;", null, label9, label16, 2);
            methodVisitor.visitLocalVariable("clusters", "Ljava/lang/String;", null, label9, label16, 3);
            methodVisitor.visitLocalVariable("udpPort", "I", null, label9, label16, 4);
            methodVisitor.visitLocalVariable("healthyOnly", "Z", null, label9, label16, 5);
            methodVisitor.visitLocalVariable("serviceInfo", "Lcom/alibaba/nacos/api/naming/pojo/ServiceInfo;", null, label0, label16, 6);
            methodVisitor.visitLocalVariable("otherServiceInfo", "Lcom/alibaba/nacos/api/naming/pojo/ServiceInfo;", null, label3, label16, 7);
            methodVisitor.visitMaxs(6, 9);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "queryService", "(Ljava/lang/String;Ljava/lang/String;)Lcom/alibaba/nacos/api/naming/pojo/Service;", null, new String[]{"com/alibaba/nacos/api/exception/NacosException"});
            methodVisitor.visitCode();
            Label label0 = new Label();
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(112, label0);
            methodVisitor.visitInsn(ACONST_NULL);
            methodVisitor.visitInsn(ARETURN);
            Label label1 = new Label();
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLocalVariable("this", "Lcn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy;", null, label0, label1, 0);
            methodVisitor.visitLocalVariable("serviceName", "Ljava/lang/String;", null, label0, label1, 1);
            methodVisitor.visitLocalVariable("groupName", "Ljava/lang/String;", null, label0, label1, 2);
            methodVisitor.visitMaxs(1, 3);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "createService", "(Lcom/alibaba/nacos/api/naming/pojo/Service;Lcom/alibaba/nacos/api/selector/AbstractSelector;)V", null, new String[]{"com/alibaba/nacos/api/exception/NacosException"});
            methodVisitor.visitCode();
            Label label0 = new Label();
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(118, label0);
            methodVisitor.visitInsn(RETURN);
            Label label1 = new Label();
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLocalVariable("this", "Lcn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy;", null, label0, label1, 0);
            methodVisitor.visitLocalVariable("service", "Lcom/alibaba/nacos/api/naming/pojo/Service;", null, label0, label1, 1);
            methodVisitor.visitLocalVariable("selector", "Lcom/alibaba/nacos/api/selector/AbstractSelector;", null, label0, label1, 2);
            methodVisitor.visitMaxs(0, 3);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "deleteService", "(Ljava/lang/String;Ljava/lang/String;)Z", null, new String[]{"com/alibaba/nacos/api/exception/NacosException"});
            methodVisitor.visitCode();
            Label label0 = new Label();
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(122, label0);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitInsn(IRETURN);
            Label label1 = new Label();
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLocalVariable("this", "Lcn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy;", null, label0, label1, 0);
            methodVisitor.visitLocalVariable("serviceName", "Ljava/lang/String;", null, label0, label1, 1);
            methodVisitor.visitLocalVariable("groupName", "Ljava/lang/String;", null, label0, label1, 2);
            methodVisitor.visitMaxs(1, 3);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "updateService", "(Lcom/alibaba/nacos/api/naming/pojo/Service;Lcom/alibaba/nacos/api/selector/AbstractSelector;)V", null, new String[]{"com/alibaba/nacos/api/exception/NacosException"});
            methodVisitor.visitCode();
            Label label0 = new Label();
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(128, label0);
            methodVisitor.visitInsn(RETURN);
            Label label1 = new Label();
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLocalVariable("this", "Lcn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy;", null, label0, label1, 0);
            methodVisitor.visitLocalVariable("service", "Lcom/alibaba/nacos/api/naming/pojo/Service;", null, label0, label1, 1);
            methodVisitor.visitLocalVariable("selector", "Lcom/alibaba/nacos/api/selector/AbstractSelector;", null, label0, label1, 2);
            methodVisitor.visitMaxs(0, 3);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "getServiceList", "(IILjava/lang/String;Lcom/alibaba/nacos/api/selector/AbstractSelector;)Lcom/alibaba/nacos/api/naming/pojo/ListView;", "(IILjava/lang/String;Lcom/alibaba/nacos/api/selector/AbstractSelector;)Lcom/alibaba/nacos/api/naming/pojo/ListView<Ljava/lang/String;>;", new String[]{"com/alibaba/nacos/api/exception/NacosException"});
            methodVisitor.visitCode();
            Label label0 = new Label();
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(133, label0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "clientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            methodVisitor.visitVarInsn(ILOAD, 1);
            methodVisitor.visitVarInsn(ILOAD, 2);
            methodVisitor.visitVarInsn(ALOAD, 3);
            methodVisitor.visitVarInsn(ALOAD, 4);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/alibaba/nacos/client/naming/remote/NamingClientProxy", "getServiceList", "(IILjava/lang/String;Lcom/alibaba/nacos/api/selector/AbstractSelector;)Lcom/alibaba/nacos/api/naming/pojo/ListView;", true);
            methodVisitor.visitInsn(ARETURN);
            Label label1 = new Label();
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLocalVariable("this", "Lcn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy;", null, label0, label1, 0);
            methodVisitor.visitLocalVariable("pageNo", "I", null, label0, label1, 1);
            methodVisitor.visitLocalVariable("pageSize", "I", null, label0, label1, 2);
            methodVisitor.visitLocalVariable("groupName", "Ljava/lang/String;", null, label0, label1, 3);
            methodVisitor.visitLocalVariable("selector", "Lcom/alibaba/nacos/api/selector/AbstractSelector;", null, label0, label1, 4);
            methodVisitor.visitMaxs(5, 5);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "subscribe", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/alibaba/nacos/api/naming/pojo/ServiceInfo;", null, new String[]{"com/alibaba/nacos/api/exception/NacosException"});
            methodVisitor.visitCode();
            Label label0 = new Label();
            Label label1 = new Label();
            Label label2 = new Label();
            methodVisitor.visitTryCatchBlock(label0, label1, label2, "java/lang/Exception");
            Label label3 = new Label();
            Label label4 = new Label();
            Label label5 = new Label();
            methodVisitor.visitTryCatchBlock(label3, label4, label5, "java/lang/Exception");
            Label label6 = new Label();
            Label label7 = new Label();
            Label label8 = new Label();
            methodVisitor.visitTryCatchBlock(label6, label7, label8, "java/lang/Exception");
            Label label9 = new Label();
            methodVisitor.visitLabel(label9);
            methodVisitor.visitLineNumber(139, label9);
            methodVisitor.visitInsn(ACONST_NULL);
            methodVisitor.visitVarInsn(ASTORE, 4);
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(141, label0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "clientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitVarInsn(ALOAD, 3);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/alibaba/nacos/client/naming/remote/NamingClientProxy", "subscribe", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/alibaba/nacos/api/naming/pojo/ServiceInfo;", true);
            methodVisitor.visitVarInsn(ASTORE, 4);
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLineNumber(144, label1);
            Label label10 = new Label();
            methodVisitor.visitJumpInsn(GOTO, label10);
            methodVisitor.visitLabel(label2);
            methodVisitor.visitLineNumber(142, label2);
            methodVisitor.visitFrame(Opcodes.F_FULL, 5, new Object[]{"cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "java/lang/String", "java/lang/String", "java/lang/String", "com/alibaba/nacos/api/naming/pojo/ServiceInfo"}, 1, new Object[]{"java/lang/Exception"});
            methodVisitor.visitVarInsn(ASTORE, 5);
            Label label11 = new Label();
            methodVisitor.visitLabel(label11);
            methodVisitor.visitLineNumber(143, label11);
            methodVisitor.visitFieldInsn(GETSTATIC, "com/alibaba/nacos/client/utils/LogUtils", "NAMING_LOGGER", "Lorg/slf4j/Logger;");
            methodVisitor.visitLdcInsn("DynamicNamingClientProxy clientProxy subscribe err.");
            methodVisitor.visitVarInsn(ALOAD, 5);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "org/slf4j/Logger", "error", "(Ljava/lang/String;Ljava/lang/Throwable;)V", true);
            methodVisitor.visitLabel(label10);
            methodVisitor.visitLineNumber(146, label10);
            methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
            methodVisitor.visitInsn(ACONST_NULL);
            methodVisitor.visitVarInsn(ASTORE, 5);
            methodVisitor.visitLabel(label3);
            methodVisitor.visitLineNumber(148, label3);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "otherClientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitVarInsn(ALOAD, 3);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/alibaba/nacos/client/naming/remote/NamingClientProxy", "subscribe", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/alibaba/nacos/api/naming/pojo/ServiceInfo;", true);
            methodVisitor.visitVarInsn(ASTORE, 5);
            methodVisitor.visitLabel(label4);
            methodVisitor.visitLineNumber(151, label4);
            methodVisitor.visitJumpInsn(GOTO, label6);
            methodVisitor.visitLabel(label5);
            methodVisitor.visitLineNumber(149, label5);
            methodVisitor.visitFrame(Opcodes.F_FULL, 6, new Object[]{"cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "java/lang/String", "java/lang/String", "java/lang/String", "com/alibaba/nacos/api/naming/pojo/ServiceInfo", "com/alibaba/nacos/api/naming/pojo/ServiceInfo"}, 1, new Object[]{"java/lang/Exception"});
            methodVisitor.visitVarInsn(ASTORE, 6);
            Label label12 = new Label();
            methodVisitor.visitLabel(label12);
            methodVisitor.visitLineNumber(150, label12);
            methodVisitor.visitFieldInsn(GETSTATIC, "com/alibaba/nacos/client/utils/LogUtils", "NAMING_LOGGER", "Lorg/slf4j/Logger;");
            methodVisitor.visitLdcInsn("DynamicNamingClientProxy otherClientProxy subscribe err.");
            methodVisitor.visitVarInsn(ALOAD, 6);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "org/slf4j/Logger", "error", "(Ljava/lang/String;Ljava/lang/Throwable;)V", true);
            methodVisitor.visitLabel(label6);
            methodVisitor.visitLineNumber(153, label6);
            methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "assist", "Lcn/polarismesh/agent/plugin/nacos/delegate/NamingClientProxyAssist;");
            methodVisitor.visitVarInsn(ALOAD, 4);
            methodVisitor.visitVarInsn(ALOAD, 5);
            methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "cn/polarismesh/agent/plugin/nacos/delegate/NamingClientProxyAssist", "mergeInstances", "(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;", false);
            methodVisitor.visitTypeInsn(CHECKCAST, "com/alibaba/nacos/api/naming/pojo/ServiceInfo");
            methodVisitor.visitLabel(label7);
            methodVisitor.visitInsn(ARETURN);
            methodVisitor.visitLabel(label8);
            methodVisitor.visitLineNumber(154, label8);
            methodVisitor.visitFrame(Opcodes.F_SAME1, 0, null, 1, new Object[]{"java/lang/Exception"});
            methodVisitor.visitVarInsn(ASTORE, 6);
            Label label13 = new Label();
            methodVisitor.visitLabel(label13);
            methodVisitor.visitLineNumber(155, label13);
            methodVisitor.visitFieldInsn(GETSTATIC, "com/alibaba/nacos/client/utils/LogUtils", "NAMING_LOGGER", "Lorg/slf4j/Logger;");
            methodVisitor.visitLdcInsn("DynamicNamingClientProxy subscribe mergeInstances failed");
            methodVisitor.visitVarInsn(ALOAD, 6);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "org/slf4j/Logger", "error", "(Ljava/lang/String;Ljava/lang/Throwable;)V", true);
            Label label14 = new Label();
            methodVisitor.visitLabel(label14);
            methodVisitor.visitLineNumber(156, label14);
            methodVisitor.visitVarInsn(ALOAD, 4);
            methodVisitor.visitInsn(ARETURN);
            Label label15 = new Label();
            methodVisitor.visitLabel(label15);
            methodVisitor.visitLocalVariable("exp", "Ljava/lang/Exception;", null, label11, label10, 5);
            methodVisitor.visitLocalVariable("exp", "Ljava/lang/Exception;", null, label12, label6, 6);
            methodVisitor.visitLocalVariable("e", "Ljava/lang/Exception;", null, label13, label15, 6);
            methodVisitor.visitLocalVariable("this", "Lcn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy;", null, label9, label15, 0);
            methodVisitor.visitLocalVariable("serviceName", "Ljava/lang/String;", null, label9, label15, 1);
            methodVisitor.visitLocalVariable("groupName", "Ljava/lang/String;", null, label9, label15, 2);
            methodVisitor.visitLocalVariable("clusters", "Ljava/lang/String;", null, label9, label15, 3);
            methodVisitor.visitLocalVariable("serviceInfo", "Lcom/alibaba/nacos/api/naming/pojo/ServiceInfo;", null, label0, label15, 4);
            methodVisitor.visitLocalVariable("otherServiceInfo", "Lcom/alibaba/nacos/api/naming/pojo/ServiceInfo;", null, label3, label15, 5);
            methodVisitor.visitMaxs(4, 7);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "unsubscribe", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V", null, new String[]{"com/alibaba/nacos/api/exception/NacosException"});
            methodVisitor.visitCode();
            Label label0 = new Label();
            Label label1 = new Label();
            Label label2 = new Label();
            methodVisitor.visitTryCatchBlock(label0, label1, label2, "java/lang/Exception");
            Label label3 = new Label();
            Label label4 = new Label();
            Label label5 = new Label();
            methodVisitor.visitTryCatchBlock(label3, label4, label5, "java/lang/Exception");
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(163, label0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "clientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitVarInsn(ALOAD, 3);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/alibaba/nacos/client/naming/remote/NamingClientProxy", "unsubscribe", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V", true);
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLineNumber(166, label1);
            methodVisitor.visitJumpInsn(GOTO, label3);
            methodVisitor.visitLabel(label2);
            methodVisitor.visitLineNumber(164, label2);
            methodVisitor.visitFrame(Opcodes.F_SAME1, 0, null, 1, new Object[]{"java/lang/Exception"});
            methodVisitor.visitVarInsn(ASTORE, 4);
            Label label6 = new Label();
            methodVisitor.visitLabel(label6);
            methodVisitor.visitLineNumber(165, label6);
            methodVisitor.visitFieldInsn(GETSTATIC, "com/alibaba/nacos/client/utils/LogUtils", "NAMING_LOGGER", "Lorg/slf4j/Logger;");
            methodVisitor.visitLdcInsn("DynamicNamingClientProxy clientProxy unsubscribe err.");
            methodVisitor.visitVarInsn(ALOAD, 4);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "org/slf4j/Logger", "error", "(Ljava/lang/String;Ljava/lang/Throwable;)V", true);
            methodVisitor.visitLabel(label3);
            methodVisitor.visitLineNumber(169, label3);
            methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "otherClientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitVarInsn(ALOAD, 3);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/alibaba/nacos/client/naming/remote/NamingClientProxy", "unsubscribe", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V", true);
            methodVisitor.visitLabel(label4);
            methodVisitor.visitLineNumber(172, label4);
            Label label7 = new Label();
            methodVisitor.visitJumpInsn(GOTO, label7);
            methodVisitor.visitLabel(label5);
            methodVisitor.visitLineNumber(170, label5);
            methodVisitor.visitFrame(Opcodes.F_SAME1, 0, null, 1, new Object[]{"java/lang/Exception"});
            methodVisitor.visitVarInsn(ASTORE, 4);
            Label label8 = new Label();
            methodVisitor.visitLabel(label8);
            methodVisitor.visitLineNumber(171, label8);
            methodVisitor.visitFieldInsn(GETSTATIC, "com/alibaba/nacos/client/utils/LogUtils", "NAMING_LOGGER", "Lorg/slf4j/Logger;");
            methodVisitor.visitLdcInsn("DynamicNamingClientProxy otherClientProxy unsubscribe err.");
            methodVisitor.visitVarInsn(ALOAD, 4);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "org/slf4j/Logger", "error", "(Ljava/lang/String;Ljava/lang/Throwable;)V", true);
            methodVisitor.visitLabel(label7);
            methodVisitor.visitLineNumber(173, label7);
            methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
            methodVisitor.visitInsn(RETURN);
            Label label9 = new Label();
            methodVisitor.visitLabel(label9);
            methodVisitor.visitLocalVariable("exp", "Ljava/lang/Exception;", null, label6, label3, 4);
            methodVisitor.visitLocalVariable("exp", "Ljava/lang/Exception;", null, label8, label7, 4);
            methodVisitor.visitLocalVariable("this", "Lcn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy;", null, label0, label9, 0);
            methodVisitor.visitLocalVariable("serviceName", "Ljava/lang/String;", null, label0, label9, 1);
            methodVisitor.visitLocalVariable("groupName", "Ljava/lang/String;", null, label0, label9, 2);
            methodVisitor.visitLocalVariable("clusters", "Ljava/lang/String;", null, label0, label9, 3);
            methodVisitor.visitMaxs(4, 5);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "isSubscribed", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z", null, new String[]{"com/alibaba/nacos/api/exception/NacosException"});
            methodVisitor.visitCode();
            Label label0 = new Label();
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(177, label0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "clientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitVarInsn(ALOAD, 3);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/alibaba/nacos/client/naming/remote/NamingClientProxy", "isSubscribed", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z", true);
            Label label1 = new Label();
            methodVisitor.visitJumpInsn(IFNE, label1);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "otherClientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitVarInsn(ALOAD, 3);
            Label label2 = new Label();
            methodVisitor.visitLabel(label2);
            methodVisitor.visitLineNumber(178, label2);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/alibaba/nacos/client/naming/remote/NamingClientProxy", "isSubscribed", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z", true);
            Label label3 = new Label();
            methodVisitor.visitJumpInsn(IFEQ, label3);
            methodVisitor.visitLabel(label1);
            methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
            methodVisitor.visitInsn(ICONST_1);
            Label label4 = new Label();
            methodVisitor.visitJumpInsn(GOTO, label4);
            methodVisitor.visitLabel(label3);
            methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
            methodVisitor.visitInsn(ICONST_0);
            methodVisitor.visitLabel(label4);
            methodVisitor.visitLineNumber(177, label4);
            methodVisitor.visitFrame(Opcodes.F_SAME1, 0, null, 1, new Object[]{Opcodes.INTEGER});
            methodVisitor.visitInsn(IRETURN);
            Label label5 = new Label();
            methodVisitor.visitLabel(label5);
            methodVisitor.visitLocalVariable("this", "Lcn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy;", null, label0, label5, 0);
            methodVisitor.visitLocalVariable("serviceName", "Ljava/lang/String;", null, label0, label5, 1);
            methodVisitor.visitLocalVariable("groupName", "Ljava/lang/String;", null, label0, label5, 2);
            methodVisitor.visitLocalVariable("clusters", "Ljava/lang/String;", null, label0, label5, 3);
            methodVisitor.visitMaxs(4, 4);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "updateBeatInfo", "(Ljava/util/Set;)V", "(Ljava/util/Set<Lcom/alibaba/nacos/api/naming/pojo/Instance;>;)V", null);
            methodVisitor.visitCode();
            Label label0 = new Label();
            Label label1 = new Label();
            Label label2 = new Label();
            methodVisitor.visitTryCatchBlock(label0, label1, label2, "java/lang/Exception");
            Label label3 = new Label();
            Label label4 = new Label();
            Label label5 = new Label();
            methodVisitor.visitTryCatchBlock(label3, label4, label5, "java/lang/Exception");
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(184, label0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "clientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/alibaba/nacos/client/naming/remote/NamingClientProxy", "updateBeatInfo", "(Ljava/util/Set;)V", true);
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLineNumber(187, label1);
            methodVisitor.visitJumpInsn(GOTO, label3);
            methodVisitor.visitLabel(label2);
            methodVisitor.visitLineNumber(185, label2);
            methodVisitor.visitFrame(Opcodes.F_SAME1, 0, null, 1, new Object[]{"java/lang/Exception"});
            methodVisitor.visitVarInsn(ASTORE, 2);
            Label label6 = new Label();
            methodVisitor.visitLabel(label6);
            methodVisitor.visitLineNumber(186, label6);
            methodVisitor.visitFieldInsn(GETSTATIC, "com/alibaba/nacos/client/utils/LogUtils", "NAMING_LOGGER", "Lorg/slf4j/Logger;");
            methodVisitor.visitLdcInsn("DynamicNamingClientProxy clientProxy updateBeatInfo err.");
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "org/slf4j/Logger", "error", "(Ljava/lang/String;Ljava/lang/Throwable;)V", true);
            methodVisitor.visitLabel(label3);
            methodVisitor.visitLineNumber(190, label3);
            methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "otherClientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/alibaba/nacos/client/naming/remote/NamingClientProxy", "updateBeatInfo", "(Ljava/util/Set;)V", true);
            methodVisitor.visitLabel(label4);
            methodVisitor.visitLineNumber(193, label4);
            Label label7 = new Label();
            methodVisitor.visitJumpInsn(GOTO, label7);
            methodVisitor.visitLabel(label5);
            methodVisitor.visitLineNumber(191, label5);
            methodVisitor.visitFrame(Opcodes.F_SAME1, 0, null, 1, new Object[]{"java/lang/Exception"});
            methodVisitor.visitVarInsn(ASTORE, 2);
            Label label8 = new Label();
            methodVisitor.visitLabel(label8);
            methodVisitor.visitLineNumber(192, label8);
            methodVisitor.visitFieldInsn(GETSTATIC, "com/alibaba/nacos/client/utils/LogUtils", "NAMING_LOGGER", "Lorg/slf4j/Logger;");
            methodVisitor.visitLdcInsn("DynamicNamingClientProxy otherClientProxy updateBeatInfo err.");
            methodVisitor.visitVarInsn(ALOAD, 2);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "org/slf4j/Logger", "error", "(Ljava/lang/String;Ljava/lang/Throwable;)V", true);
            methodVisitor.visitLabel(label7);
            methodVisitor.visitLineNumber(194, label7);
            methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
            methodVisitor.visitInsn(RETURN);
            Label label9 = new Label();
            methodVisitor.visitLabel(label9);
            methodVisitor.visitLocalVariable("exp", "Ljava/lang/Exception;", null, label6, label3, 2);
            methodVisitor.visitLocalVariable("exp", "Ljava/lang/Exception;", null, label8, label7, 2);
            methodVisitor.visitLocalVariable("this", "Lcn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy;", null, label0, label9, 0);
            methodVisitor.visitLocalVariable("modifiedInstances", "Ljava/util/Set;", "Ljava/util/Set<Lcom/alibaba/nacos/api/naming/pojo/Instance;>;", label0, label9, 1);
            methodVisitor.visitMaxs(3, 3);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "serverHealthy", "()Z", null, null);
            methodVisitor.visitCode();
            Label label0 = new Label();
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(198, label0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "clientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/alibaba/nacos/client/naming/remote/NamingClientProxy", "serverHealthy", "()Z", true);
            methodVisitor.visitInsn(IRETURN);
            Label label1 = new Label();
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLocalVariable("this", "Lcn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy;", null, label0, label1, 0);
            methodVisitor.visitMaxs(1, 1);
            methodVisitor.visitEnd();
        }
        {
            methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "shutdown", "()V", null, new String[]{"com/alibaba/nacos/api/exception/NacosException"});
            methodVisitor.visitCode();
            Label label0 = new Label();
            Label label1 = new Label();
            Label label2 = new Label();
            methodVisitor.visitTryCatchBlock(label0, label1, label2, "java/lang/Exception");
            Label label3 = new Label();
            Label label4 = new Label();
            Label label5 = new Label();
            methodVisitor.visitTryCatchBlock(label3, label4, label5, "java/lang/Exception");
            methodVisitor.visitLabel(label0);
            methodVisitor.visitLineNumber(204, label0);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "clientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/alibaba/nacos/client/naming/remote/NamingClientProxy", "shutdown", "()V", true);
            methodVisitor.visitLabel(label1);
            methodVisitor.visitLineNumber(207, label1);
            methodVisitor.visitJumpInsn(GOTO, label3);
            methodVisitor.visitLabel(label2);
            methodVisitor.visitLineNumber(205, label2);
            methodVisitor.visitFrame(Opcodes.F_SAME1, 0, null, 1, new Object[]{"java/lang/Exception"});
            methodVisitor.visitVarInsn(ASTORE, 1);
            Label label6 = new Label();
            methodVisitor.visitLabel(label6);
            methodVisitor.visitLineNumber(206, label6);
            methodVisitor.visitFieldInsn(GETSTATIC, "com/alibaba/nacos/client/utils/LogUtils", "NAMING_LOGGER", "Lorg/slf4j/Logger;");
            methodVisitor.visitLdcInsn("DynamicNamingClientProxy clientProxy shutdown err.");
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "org/slf4j/Logger", "error", "(Ljava/lang/String;Ljava/lang/Throwable;)V", true);
            methodVisitor.visitLabel(label3);
            methodVisitor.visitLineNumber(210, label3);
            methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
            methodVisitor.visitVarInsn(ALOAD, 0);
            methodVisitor.visitFieldInsn(GETFIELD, "cn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy", "otherClientProxy", "Lcom/alibaba/nacos/client/naming/remote/NamingClientProxy;");
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/alibaba/nacos/client/naming/remote/NamingClientProxy", "shutdown", "()V", true);
            methodVisitor.visitLabel(label4);
            methodVisitor.visitLineNumber(213, label4);
            Label label7 = new Label();
            methodVisitor.visitJumpInsn(GOTO, label7);
            methodVisitor.visitLabel(label5);
            methodVisitor.visitLineNumber(211, label5);
            methodVisitor.visitFrame(Opcodes.F_SAME1, 0, null, 1, new Object[]{"java/lang/Exception"});
            methodVisitor.visitVarInsn(ASTORE, 1);
            Label label8 = new Label();
            methodVisitor.visitLabel(label8);
            methodVisitor.visitLineNumber(212, label8);
            methodVisitor.visitFieldInsn(GETSTATIC, "com/alibaba/nacos/client/utils/LogUtils", "NAMING_LOGGER", "Lorg/slf4j/Logger;");
            methodVisitor.visitLdcInsn("DynamicNamingClientProxy otherClientProxy shutdown err.");
            methodVisitor.visitVarInsn(ALOAD, 1);
            methodVisitor.visitMethodInsn(INVOKEINTERFACE, "org/slf4j/Logger", "error", "(Ljava/lang/String;Ljava/lang/Throwable;)V", true);
            methodVisitor.visitLabel(label7);
            methodVisitor.visitLineNumber(214, label7);
            methodVisitor.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
            methodVisitor.visitInsn(RETURN);
            Label label9 = new Label();
            methodVisitor.visitLabel(label9);
            methodVisitor.visitLocalVariable("exp", "Ljava/lang/Exception;", null, label6, label3, 1);
            methodVisitor.visitLocalVariable("exp", "Ljava/lang/Exception;", null, label8, label7, 1);
            methodVisitor.visitLocalVariable("this", "Lcn/polarismesh/agent/plugin/nacos/delegate/DynamicNamingClientProxy;", null, label0, label9, 0);
            methodVisitor.visitMaxs(3, 2);
            methodVisitor.visitEnd();
        }
        classWriter.visitEnd();

        return classWriter.toByteArray();

    }

}
