server.port=0
spring.application.name=sb-dubbo-provider
# Dubbo 配置
dubbo.application.name=sb-dubbo-provider
#dubbo.application.metadataType=local
dubbo.registry.address=zookeeper://127.0.0.1:2181
dubbo.registries.nacos.address=nacos://9.135.13.199:8848
dubbo.protocol.name=dubbo
dubbo.protocol.port=20880
dubbo.application.qosEnable=false
