server.port=17081
spring.application.name=sc-dubbo-consumer
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.cloud.nacos.discovery.enabled=true
spring.cloud.nacos.username=nacos
spring.cloud.nacos.password=nacos
dubbo.application.name=sc-dubbo-consumer
dubbo.registry.address=nacos://127.0.0.1:8848
dubbo.protocol.name=dubbo
dubbo.protocol.port=30880
dubbo.consumer.timeout=3000
dubbo.application.qosEnable=false
management.endpoints.web.exposure.include=*
spring.main.allow-circular-references=true
