---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-consumer-2022
  name: service-consumer-2022
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-consumer-2022
  template:
    metadata:
      labels:
        app: service-consumer-2022
      annotations:
        polarismesh.cn/javaagent: "true"
        polarismesh.cn/javaagentConfig: |
          {
          	"spring.cloud.polaris.circuitbreaker.enabled": "true",
            "spring.cloud.polaris.lossless.enabled": "true",
            "spring.cloud.polaris.router.enabled": "true"
          }
    spec:
      containers:
        - image: polarismesh/polaris-javaagent-demo-sc-quickstart-2022-consumer:2.0.1.0-java17
          imagePullPolicy: Always
          name: consumer
          resources:
            limits:
              cpu: "500m"
              memory: 1000Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          command:
            - /bin/bash
            - -c
            - cd /app && java -Dserver.port=65002 -Dspring.cloud.nacos.config.enabled=false -jar main.jar
          lifecycle:
            preStop:
              exec:
                command: [ "curl","-X","PUT","http://127.0.0.1:28080/offline","&&","sleep","30" ]
          readinessProbe:
            httpGet:
              path: /online
              port: 28080
            initialDelaySeconds: 3
            periodSeconds: 3
      restartPolicy: Always