server.port=17082
spring.application.name=sb-dubbo-consumer
# Dubbo 配置
dubbo.application.name=sb-dubbo-consumer
dubbo.registry.address=zookeeper://127.0.0.1:2181
dubbo.protocol.name=dubbo
dubbo.protocol.port=30880
dubbo.consumer.timeout=3000
dubbo.application.qosEnable=false
