# application
dubbo.application.name=dubbo-agent-example-provider
dubbo.application.qosEnable=false
# registry
dubbo.registry.address=nacos://127.0.0.1:8848
# protocol
dubbo.protocol.name=dubbo
dubbo.protocol.port=20880
dubbo.config-center.address=zookeeper://127.0.0.1:2181