---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-provider-2022-b
  name: service-provider-2022-b
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-provider-2022-b
  template:
    metadata:
      labels:
        app: service-provider-2022-b
      annotations:
        polarismesh.cn/javaagent: "true"
    spec:
      containers:
        - image: polarismesh/polaris-javaagent-demo-sc-quickstart-2022-provider-b:2.0.2-RC1-java17
          imagePullPolicy: Always
          name: provider
          resources:
            limits:
              cpu: "500m"
              memory: 1000Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          command:
            - /bin/bash
            - -c
            - cd /app && java -Dserver.port=65004 -jar main.jar
          lifecycle:
            preStop:
              exec:
                command: [ "curl","-X","PUT","http://127.0.0.1:28080/offline","&&","sleep","30" ]
          readinessProbe:
            httpGet:
              path: /online
              port: 28080
            initialDelaySeconds: 3
            periodSeconds: 3
      restartPolicy: Always