---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-c-hoxton
  name: service-c-hoxton
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c-hoxton
  template:
    metadata:
      labels:
        app: service-c-hoxton
      annotations:
        polarismesh.cn/javaagent: "true"
        polarismesh.cn/javaagentVersion: "1.7.0-RC4"
        polarismesh.cn/javaagentFrameworkName: "spring-cloud"
        polarismesh.cn/javaagentFrameworkVersion: "hoxton"
    spec:
      containers:
        - image: polarismesh/polaris-javaagent-demo-sc-gray-hoxton-service-c:1.7.0-java8
          imagePullPolicy: Always
          name: consumer
          resources:
            limits:
              cpu: "500m"
              memory: 1000Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          command:
            - /bin/bash
            - -c
            - cd /app && java -Dserver.port=65201 -jar main.jar
          lifecycle:
            preStop:
              exec:
                command: [ "curl","-X","PUT","http://127.0.0.1:28080/offline","&&","sleep","30" ]
          readinessProbe:
            httpGet:
              path: /online
              port: 28080
            initialDelaySeconds: 3
            periodSeconds: 3
      restartPolicy: Always