server.port=0
spring.application.name=sc-dubbo-provider
# Nacos 服务注册发现（Agent 会替换为 Polaris）
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.cloud.nacos.discovery.enabled=true
spring.cloud.nacos.username=nacos
spring.cloud.nacos.password=nacos
# Dubbo 配置
dubbo.application.name=sc-dubbo-provider
dubbo.registry.address=nacos://127.0.0.1:8848
dubbo.protocol.name=dubbo
dubbo.protocol.port=20880
dubbo.application.qosEnable=false
# Actuator
management.endpoints.web.exposure.include=*
spring.main.allow-circular-references=true
